name: CICD

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: python -m pip install pytest && pip install "fastapi[all]" && pip install pytest-cov

      - name: Run Failed Login Test
        run: pytest app/test_bad_token.py --cov=app.main

      - name: Run Empty Database Tests
        run: pytest app/test_empty.py --cov=app.main

      - name: Run Simple Sequence Tests
        run: pytest app/test_simple.py --cov=app.main

      - name: Run Complex Sequence Tests
        run: pytest app/test_complex.py --cov=app.main

      - name: Run Parametrized Tests
        run: pytest app/test_parametrize.py --cov=app.main

      - name: Run All Tests
        run: pytest --cov=app.main
