image: python:3.10

stages:
  - test

cache:
  paths:
    - .venv

before_script:
  - python -m venv .venv
  - .venv/bin/pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest tests
