name: CICD

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: python -m pip install pytest && pip install "fastapi[all]" && pip install pytest-cov

      - name: Run Tests
        run: pytest --cov=app.main
